### ISSUE TITLE
Link to LinkedIn profile is not absolute

### ISSUE THREAD

**Issue by myTerminal** [JavaScriptErika/JavaScriptErika.github.io#1]
https://github.com/JavaScriptErika/JavaScriptErika.github.io/blob/d0675319923642074b84d6e12fa5e7f3618200ef/src/Components/CubeSide.js#L13

Does not take you to LinkedIn, should be https://www.linkedin.com/in/erika-ritter instead.

**Comment by JavaScriptErika** [comment]
Thank you @myTerminal  for pointing that out. I'll make that change!

**Comment by JavaScriptErika** [comment]
Has been fixed!
